### ISSUE TITLE
Mistake found: google analytics broken

### ISSUE THREAD

**Issue by wcornwell** [nicercode/EnvironmentalComputing#36]
**Which page(s) do this mistake(s) pertain to?**
All

**Describe the error(s)** 
Google analytics broken

**Additional context** 
the two different partials/header.html files seem to not be playing nicely together.

**Comment by dfalster** [comment]
On Netlify, I downloaded the deployment from Feb 4 (commit [1db7d10](https://github.com/nicercode/EnvironmentalComputing/commit/1db7d102d552ec0c8358a2122aca289d0869a328)) and Feb 9(commit [9447b0b](https://github.com/nicercode/EnvironmentalComputing/commit/9447b0b2768da66061d013b51a06df071b9e5783)) and then compared them using git to see if there were any differences. Indeed it seems all the google analytics stuff has been removed

<img width="722" alt="image" src="https://user-images.githubusercontent.com/3589590/153937399-dfaa42e4-336c-49de-95e5-686598e7488f.png">


I'll now look at the code to see if I can figure out why

**Comment by dfalster** [comment]
Here's the code comparison

https://github.com/nicercode/EnvironmentalComputing/compare/1db7d10...9447b0b

The issue is (as Will suggested) addition of new page [layouts/partials/header.html](https://github.com/nicercode/EnvironmentalComputing/issues/36#diff-42986cf40ad96f5b7ca39d9b71ba6a9f252656de24cfe82100892ff0f4400f90) This overrides the one in `themes/hugo-theme-learn/layouts/partials/header.html`. But that is where we added the google analytics code in https://github.com/nicercode/EnvironmentalComputing/commit/ca84bf596b59376d4c23a94926f773e1c5541785 (#21).

It's actually good to keep our own copy of the partials so I'll just add google analytics back in (see [d7ba9c7](https://github.com/nicercode/EnvironmentalComputing/commit/d7ba9c79bbb643899de29d292a2250bab924f509))

**Comment by dfalster** [comment]
I now have access to analytics (thanks @wcornwell ) and seems to be working.
